# Generated by Django 3.0.10 on 2020-09-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matshare", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursestudentsubscription",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="When you've finished a course, make its subscription inactive. Inactive subscriptions don't trigger material notification mails and the course won't appear in dashboard and material feed. However, you will retain your permission to access the course and its material via the course directory.",
                verbose_name="active",
            ),
        ),
        migrations.AlterIndexTogether(
            name="coursestudentsubscription",
            index_together={("course", "user", "active")},
        ),
    ]
