# Generated by Django 3.0.10 on 2020-09-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matshare", "0002_auto_20200920_1530"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="course",
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name="coursestudentsubscription",
            index_together={("user", "active")},
        ),
    ]
