# Adjust settings for development mode

version: "3.6"

services:
  uwsgi:
    environment:
      MS_DEBUG: 1
      # Debug logging is very verbose, so the loggers for which to enable it have
      # to be listed explicitly, comma-separated
      #MS_DEBUG_LOGGERS: "matshare,django.request"
      MS_SECRET_KEY: something unsecure for development
      MS_TIME_ZONE: Europe/Berlin
      MS_URL: http://dd.dyn.efficiosoft.com:58080
      MS_DEFAULT_FROM_EMAIL: "MatShare <matshare@shajil.de>"
      MS_EMAIL_HOST: 10.64.0.1
      MS_COURSE_CONTRIBUTOR: AG SBS
      MS_COURSE_PUBLISHER: TU Dresden
      MS_NUM_PROCESSES: 2
      MS_NUM_THREADS: 2
      MS_NUM_SPOOLER_PROCESSES: 2
      MS_GIT_ASYNC: 20
      # Check every second for changes in Python modules and reload if needed
      MS_PY_AUTO_RELOAD: 1
      # Kill workers after 1 second if they take longer to shutdown
      MS_WORKER_RELOAD_MERCY: 1
    volumes:
    # Mount source code into the container read-only for auto-reloading to work.
    # Note that this causes the translation files compiled into the image to be
    # unavailable, so you need to run "./manage.py compilemessages" outside the
    # container to have the *.mo files available in the mounted directory.
    - ./matshare:/opt/matshare/matshare:ro
    - ./git_hooks:/opt/matshare/git_hooks:ro
    - ./git_initial:/opt/matshare/git_initial:ro
    - ./uwsgi_configs:/opt/matshare/uwsgi_configs:ro

  nginx:
    ports:
    - 58080:80/tcp
    volumes:
    # Allow editing config without rebuilding
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
