version: "3.6"

services:
  uwsgi:
    build: .
    depends_on:
    - db
    environment:
      MS_DB_HOST: db
      MS_DB_NAME: postgres
      MS_DB_USER: postgres
      MS_DB_PASSWORD: postgres
    hostname: uwsgi
    image: matshare_uwsgi:latest
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./data:/opt/matshare/data

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    hostname: postgres
    image: postgres:13.1-alpine
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./pgdata:/var/lib/postgresql/data

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    hostname: nginx
    image: matshare_nginx
    ports:
    - 8000:80/tcp
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
