#!/usr/bin/env -S ./scripts/config /bin/bash -e
# The docker main command.

echo '
*********************
* This is MatShare. *
*********************
'

if [ ! -z "$MS_DATABASE_HOST" ] && [ ! -z "$MS_DATABASE_PORT" ]; then
    echo "Waiting for database on ${MS_DATABASE_HOST}:${MS_DATABASE_PORT} ..."
    while ! nc -z "$MS_DATABASE_HOST" "$MS_DATABASE_PORT"; do sleep 1; done;
    echo
fi

export DJANGO_SETTINGS_MODULE=matshare.settings

./scripts/init_or_upgrade
echo

# Run the server
exec /opt/uwsgi/uwsgi --plugin-dir=/opt/uwsgi --emperor=uwsgi_configs --vassal-set=plugin-dir=/opt/uwsgi --vassal-set=chdir=..
